# Generated by Django 4.0.4 on 2023-03-24 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def associate_notes_with_first_user(apps, schema_editor):
    Note = apps.get_model('notes', 'Note')
    User = apps.get_model('auth', 'User')

    first_user = User.objects.first()
    if first_user:
        Note.objects.update(user=first_user)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(associate_notes_with_first_user),
    ]
